### PR TITLE
changes to make it react 16 friendly

### PR DESCRIPTION
**Pull request by phyzical**
Adds logic to make package react-16 friendly

Tested the jobs page still works

### CODE REVIEW

**Review by willagw — APPROVED** [review]

**Comment by willagw** [comment]
This still works fine with the current prod React version right? It just seems like there's no packaging or real version control on this repo. :/ :)

**Comment by phyzical** [comment]
yeah correct im still doing my testing with react 15

**Comment by stwr667** [comment]
image

@phyzical there are a few pages that use the date-range functionality, but not all (OTOH). Worth checking them out too, e.g. prescriptions.

**Comment by phyzical** [comment]
that seems to work on the prescriptions page also

**Pull request merged**
